### ISSUE TITLE
Rails 5 undefined method hide_action

### ISSUE THREAD

**Issue by mensfeld** [hashrocket/decent_exposure#135]
Hey, when I try to run Rails 5 beta app, I get this error:

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /app/config/application.rb:6)
/gems/decent_exposure-2.3.2/lib/decent_exposure/expose.rb:14:in `block in extended': undefined method `hide_action' for ActionController::Base:Class (NoMethodError)
	from /gems/decent_exposure-2.3.2/lib/decent_exposure/expose.rb:7:in `class_eval'
	from /gems/decent_exposure-2.3.2/lib/decent_exposure/expose.rb:7:in `extended'
	from /gems/decent_exposure-2.3.2/lib/decent_exposure.rb:5:in `extend'
	from /gems/decent_exposure-2.3.2/lib/decent_exposure.rb:5:in `block in <top (required)>'
	from /gems/activesupport-5.0.0.beta1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /gems/activesupport-5.0.0.beta1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /gems/activesupport-5.0.0.beta1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /gems/activesupport-5.0.0.beta1/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /gems/activesupport-5.0.0.beta1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /gems/actionpack-5.0.0.beta1/lib/action_controller/base.rb:262:in `<class:Base>'
	from /gems/actionpack-5.0.0.beta1/lib/action_controller/base.rb:164:in `<module:ActionController>'
	from /gems/actionpack-5.0.0.beta1/lib/action_controller/base.rb:5:in `<top (required)>'
	from /bundler/gems/ransack-2a3759317a44/lib/ransack.rb:38:in `<top (required)>'
	from /gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /app/config/application.rb:6:in `<top (required)>'
	from /gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:88:in `require'
	from /gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
	from /gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /gems/railties-5.0.0.beta1/lib/rails/command.rb:20:in `run'
	from /gems/railties-5.0.0.beta1/lib/rails/commands.rb:19:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
[Senpuu (master)]$ 

```

**Comment by mattpolito** [comment]
@mensfeld Thanks very much for bringing this to our attention. There is actually another pull-request (#121) that fixes this. I'll look into getting this fixed asap.

**Comment by mensfeld** [comment]
@mattpolito  you are welcome. Here's a temporary patch for that issue: http://dev.mensfeld.pl/2015/12/upgrading-to-ruby-on-rails-5-0-from-rails-4-2-application-use-case/

**Comment by mattpolito** [comment]
This is addressed in v.2.3.3
